# Generated by Django 6.0.5 on 2026-05-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Assigned', max_length=50)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.claim')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.volunteer')),
            ],
        ),
    ]
