# Generated by Django 6.0.5 on 2026-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('person', 'Person'), ('ngo', 'NGO'), ('restaurant', 'Restaurant')], default='person', max_length=20),
        ),
    ]
