# Generated by Django 6.0.5 on 2026-05-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteer_images/'),
        ),
    ]
